server:
  port: 8888

management:
  context-path: /admin
  
cloudfoundry:
  service:
    broker:
      description: Spring platform config server
    definition:
      metadata:
        uri: http://localhost:${server.port}

eureka:
  instance:
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
    