server:
  port: 8888

management:
  context-path: /admin
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    
encrypt:
  keyStore:
    location: classpath:keystore.jks
    password: foobar
    alias: test

eureka:
  instance:
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health

spring:
  platform:
    config:
      server:
        uri: https://github.com/spring-platform-samples/config-repo
        basedir: target/config

# TODO: move these profiles to the remote repo

---
spring:
  profiles: cloud
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://${PREFIX:}eureka.${application.domain:cfapps.io}}/v2/
  instance:
    hostname: ${PREFIX:}${spring.application.name}.${application.domain:cfapps.io}
    nonSecurePort: 80
